### ISSUE TITLE
@Michael: test if one service from one docker-compose can access a service from another docker-compose

### ISSUE THREAD

**Issue by MichaelLangbein** [riesgos/buildall#6]
Can verify that this works
To reproduce, try something like this:

receiver/receiver.py:
```python
from flask import Flask, render_template
import os

app = Flask(__name__)


@app.route('/')
def home():
    return "Hello there!"


if __name__ == "__main__":
    port = int(os.environ.get('PORT', 5000))
    app.run(debug=True, host='0.0.0.0', port=port)
```

receiver/Dockerfile:
```docker
# start by pulling the python image
FROM python:3.8-alpine

# copy the requirements file into the image
COPY ./requirements.txt /app/requirements.txt

# switch working directory
WORKDIR /app

# install the dependencies and packages in the requirements file
RUN pip install -r requirements.txt

# copy every content from the local file to the image
COPY . /app

# configure the container to run in an executed manner
ENTRYPOINT [ "python" ]
CMD ["main.py" ]
```

receiver/receiver.yml:
```yml
version: "3"


services:
  
  receiver: 
    build:
      context: ./receiver/rcvr
    environment:
      PORT: 5000
    ports:
      - 5000:5000
```

sender/sender.py:
```python
from flask import Flask, render_template
import os
import requests

app = Flask(__name__)


@app.route('/')
def home():
    result = requests.get(url="http://receiver:5000/")
    print(result.text)
    return "Got response from receiver: " + result.text


if __name__ == "__main__":
    port = int(os.environ.get('PORT', 5001))
    app.run(debug=True, host='0.0.0.0', port=port)
```

sender/Dockerfile:
```docker
# start by pulling the python image
FROM python:3.8-alpine

# copy the requirements file into the image
COPY ./requirements.txt /app/requirements.txt

# switch working directory
WORKDIR /app

# install the dependencies and packages in the requirements file
RUN pip install -r requirements.txt

# copy every content from the local file to the image
COPY . /app

# configure the container to run in an executed manner
ENTRYPOINT [ "python" ]
CMD ["main.py" ]
```

sender/sender.yml
```yml
version: "3"

services:

  sender: 
    build:
      context: ./sender/sdr
    environment:
      PORT: 5001
    ports:
      - 5001:5001
```

Executing:
```bash
#! /bin/bash

echo "Effective configuration:"
sudo docker compose -f ./receiver/receiver.yml -f ./sender/sender.yml config

echo "Starting services ..."
sudo docker compose -f ./receiver/receiver.yml -f ./sender/sender.yml up -d
echo "Services started."
```
